n=int(input("enter you are:"))
i=1
while i<=n:
    j=1
    while j<=10:
        print(i,"*",j,"=",i*j)
        j+=1
    i+=1
n=int(input("enter a number:"))
i=1
while i<=n:
    j=1
    while j<=10:
        print(i,"*",j,"=",i*j)
        j=j+1
    i=i+1